"""saved_outfits

Revision ID: 1e8178fdc3d5
Revises: 18daf100e59f
Create Date: 2026-08-16 00:31:43.269660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8178fdc3d5'
down_revision: Union[str, Sequence[str], None] = '18daf100e59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_outfits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_outfits_user_id'), 'saved_outfits', ['user_id'], unique=False)
    op.create_table('saved_outfit_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('saved_outfit_id', sa.UUID(), nullable=False),
    sa.Column('wardrobe_item_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['saved_outfit_id'], ['saved_outfits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wardrobe_item_id'], ['wardrobe_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_outfit_items')
    op.drop_index(op.f('ix_saved_outfits_user_id'), table_name='saved_outfits')
    op.drop_table('saved_outfits')
    # ### end Alembic commands ###
